/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiV1RouteImport } from './routes/api/v1'
import { Route as ApiVideosRouteImport } from './routes/api/videos'
import { Route as StudioProjectIdRouteImport } from './routes/studio/$projectId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiSystemDevicesRouteImport } from './routes/api/system.devices'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Route = ApiV1RouteImport.update({
  id: '/api/v1',
  path: '/api/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideosRoute = ApiVideosRouteImport.update({
  id: '/api/videos',
  path: '/api/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioProjectIdRoute = StudioProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => StudioRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemDevicesRoute = ApiSystemDevicesRouteImport.update({
  id: '/api/system/devices',
  path: '/api/system/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiV1Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/studio': typeof StudioRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/models': typeof ApiModelsRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/api/videos': typeof ApiVideosRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/system/devices': typeof ApiSystemDevicesRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/studio': typeof StudioRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/models': typeof ApiModelsRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/api/videos': typeof ApiVideosRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/system/devices': typeof ApiSystemDevicesRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/studio': typeof StudioRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/models': typeof ApiModelsRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/api/videos': typeof ApiVideosRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/system/devices': typeof ApiSystemDevicesRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/studio'
    | '/api/health'
    | '/api/mcp'
    | '/api/models'
    | '/api/v1'
    | '/api/videos'
    | '/studio/$projectId'
    | '/api/auth/$'
    | '/api/system/devices'
    | '/api/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/studio'
    | '/api/health'
    | '/api/mcp'
    | '/api/models'
    | '/api/v1'
    | '/api/videos'
    | '/studio/$projectId'
    | '/api/auth/$'
    | '/api/system/devices'
    | '/api/v1/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/studio'
    | '/api/health'
    | '/api/mcp'
    | '/api/models'
    | '/api/v1'
    | '/api/videos'
    | '/studio/$projectId'
    | '/api/auth/$'
    | '/api/system/devices'
    | '/api/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  StudioRoute: typeof StudioRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiV1Route: typeof ApiV1RouteWithChildren
  ApiVideosRoute: typeof ApiVideosRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSystemDevicesRoute: typeof ApiSystemDevicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1': {
      id: '/api/v1'
      path: '/api/v1'
      fullPath: '/api/v1'
      preLoaderRoute: typeof ApiV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/videos': {
      id: '/api/videos'
      path: '/api/videos'
      fullPath: '/api/videos'
      preLoaderRoute: typeof ApiVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$projectId': {
      id: '/studio/$projectId'
      path: '/$projectId'
      fullPath: '/studio/$projectId'
      preLoaderRoute: typeof StudioProjectIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/devices': {
      id: '/api/system/devices'
      path: '/api/system/devices'
      fullPath: '/api/system/devices'
      preLoaderRoute: typeof ApiSystemDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof ApiV1Route
    }
  }
}

interface StudioRouteChildren {
  StudioProjectIdRoute: typeof StudioProjectIdRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioProjectIdRoute: StudioProjectIdRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

interface ApiV1RouteChildren {
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

const ApiV1RouteChildren: ApiV1RouteChildren = {
  ApiV1SplatRoute: ApiV1SplatRoute,
}

const ApiV1RouteWithChildren = ApiV1Route._addFileChildren(ApiV1RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  StudioRoute: StudioRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiV1Route: ApiV1RouteWithChildren,
  ApiVideosRoute: ApiVideosRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSystemDevicesRoute: ApiSystemDevicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
